### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by AkioSarkiz** [yesfedor/cms#1]
If you need progressive cms, you must create an mvc system. It's bad when a performance is mixed with php code. Because it is difficult to maintain and read.

**Comment by yesfedor** [comment]
I tried writing a cms without realizing it yet, now I've switched to vue 3 + REST API

**Comment by yesfedor** [comment]
> If you need progressive cms, you must create an mvc system. It's bad when a performance is mixed with php code. Because it is difficult to maintain and read.

I tried writing a cms without realizing it yet, now I've switched to vue 3 + REST API
